# Generated by Django 2.0.13 on 2021-08-03 21:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='highflow',
            fields=[
                ('FolderNo', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(75)])),
                ('RedScore', models.PositiveIntegerField(default=1)),
                ('Archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='sats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Sats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(100)])),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vhwhighflow.highflow')),
            ],
        ),
    ]
